spring.application.name=SkyGradU
server.error.include-exception=TRUE
server.error.include-stacktrace=ALWAYS
spring.mvc.static-path-pattern=/webapp/**

spring.datasource.url=jdbc:mysql://skygradu.mysql.database.azure.com/skygradu
spring.datasource.username=jjonghwa
spring.datasource.password=jhmun0823!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update